### ISSUE TITLE
Your example doesn't work

### ISSUE THREAD

**Issue by ykmargate** [ReactjsProgram/React-Fundamentals#31]
I downloaded your repository.
Executed npm install
when I tried to execute npm run I got error
ERROR in ./app/config/routes.js
Module parse failed: C:\React-Fundamentals-video12\app\config\routes.js Unexpected token (14:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (14:2)
    at Parser.pp$4.raise (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)

**Comment by coaxial** [comment]
Are you using Node >= 4 and an up to date `npm`?

``` bash
git checkout video13
npm i
npm run start
open localhost:8080/webpack-dev-server
```

**Comment by ykmargate** [comment]
Node 4.5.0 and npm was a part of Node (Windows installation)

**Comment by ykmargate** [comment]
> gh-battle@1.0.0 start C:\React-Fundamentals-video12
> webpack-dev-server

 http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from C:\React-Fundamentals-video12
Hash: bc35c808c4d80ffb4ff2
Version: webpack 1.13.2
Time: 1498ms
          Asset       Size  Chunks             Chunk Names
index_bundle.js     680 kB       0  [emitted]  main
     index.html  314 bytes          [emitted]  
chunk    {0} index_bundle.js (main) 646 kB [rendered]
    [0] multi main 28 bytes {0} [built]
    [1] ./app/index.js 165 bytes {0} [built] [1 error]
    [2] ./~/react/react.js 56 bytes {0} [built]
    [3] ./~/react/lib/React.js 1.49 kB {0} [built]
    [4] ./~/react/lib/ReactDOM.js 3.71 kB {0} [built]
    [5](webpack)/~/node-libs-browser/~/process/browser.js 5.3 kB {0} [built]
    [6] ./~/react/lib/ReactCurrentOwner.js 653 bytes {0} [built]
    [7] ./~/react/lib/ReactDOMTextComponent.js 4.32 kB {0} [built]
    [8] ./~/react/lib/DOMChildrenOperations.js 5 kB {0} [built]
    [9] ./~/react/lib/Danger.js 6.96 kB {0} [built]
   [10] ./~/react/~/fbjs/lib/ExecutionEnvironment.js 1.09 kB {0} [built]
   [11] ./~/react/~/fbjs/lib/createNodesFromMarkup.js 2.71 kB {0} [built]
   [12] ./~/react/~/fbjs/lib/createArrayFromMixed.js 2.36 kB {0} [built]
   [13] ./~/react/~/fbjs/lib/toArray.js 1.98 kB {0} [built]
   [14] ./~/react/~/fbjs/lib/invariant.js 1.51 kB {0} [built]
   [15] ./~/react/~/fbjs/lib/getMarkupWrap.js 3.06 kB {0} [built]
   [16] ./~/react/~/fbjs/lib/emptyFunction.js 1.09 kB {0} [built]
   [17] ./~/react/lib/ReactMultiChildUpdateTypes.js 861 bytes {0} [built]
   [18] ./~/react/~/fbjs/lib/keyMirror.js 1.27 kB {0} [built]
   [19] ./~/react/lib/ReactPerf.js 2.51 kB {0} [built]
   [20] ./~/react/lib/setInnerHTML.js 3.35 kB {0} [built]
   [21] ./~/react/lib/setTextContent.js 1.2 kB {0} [built]
   [22] ./~/react/lib/escapeTextContentForBrowser.js 849 bytes {0} [built]
   [23] ./~/react/lib/DOMPropertyOperations.js 7.88 kB {0} [built]
   [24] ./~/react/lib/DOMProperty.js 9.57 kB {0} [built]
   [25] ./~/react/lib/quoteAttributeValueForBrowser.js 746 bytes {0} [built]
   [26] ./~/react/~/fbjs/lib/warning.js 1.77 kB {0} [built]
   [27] ./~/react/lib/ReactComponentBrowserEnvironment.js 1.26 kB {0} [built]
   [28] ./~/react/lib/ReactDOMIDOperations.js 3.29 kB {0} [built]
   [29] ./~/react/lib/ReactMount.js 36.8 kB {0} [built]
   [30] ./~/react/lib/ReactBrowserEventEmitter.js 12.4 kB {0} [built]
   [31] ./~/react/lib/EventConstants.js 2.04 kB {0} [built]
   [32] ./~/react/lib/EventPluginHub.js 9.22 kB {0} [built]
   [33] ./~/react/lib/EventPluginRegistry.js 8.41 kB {0} [built]
   [34] ./~/react/lib/EventPluginUtils.js 6.79 kB {0} [built]
   [35] ./~/react/lib/ReactErrorUtils.js 2.27 kB {0} [built]
   [36] ./~/react/lib/accumulateInto.js 1.74 kB {0} [built]
   [37] ./~/react/lib/forEachAccumulated.js 893 bytes {0} [built]
   [38] ./~/react/lib/ReactEventEmitterMixin.js 1.3 kB {0} [built]
   [39] ./~/react/lib/ViewportMetrics.js 638 bytes {0} [built]
   [40] ./~/react/lib/Object.assign.js 1.26 kB {0} [built]
   [41] ./~/react/lib/isEventSupported.js 1.97 kB {0} [built]
   [42] ./~/react/lib/ReactDOMFeatureFlags.js 458 bytes {0} [built]
   [43] ./~/react/lib/ReactElement.js 8.07 kB {0} [built]
   [44] ./~/react/lib/canDefineProperty.js 629 bytes {0} [built]
   [45] ./~/react/lib/ReactEmptyComponentRegistry.js 1.38 kB {0} [built]
   [46] ./~/react/lib/ReactInstanceHandles.js 10.6 kB {0} [built]
   [47] ./~/react/lib/ReactRootIndex.js 723 bytes {0} [built]
   [48] ./~/react/lib/ReactInstanceMap.js 1.25 kB {0} [built]
   [49] ./~/react/lib/ReactMarkupChecksum.js 1.39 kB {0} [built]
   [50] ./~/react/lib/adler32.js 1.2 kB {0} [built]
   [51] ./~/react/lib/ReactReconciler.js 3.55 kB {0} [built]
   [52] ./~/react/lib/ReactRef.js 2.34 kB {0} [built]
   [53] ./~/react/lib/ReactOwner.js 3.45 kB {0} [built]
   [54] ./~/react/lib/ReactUpdateQueue.js 10.9 kB {0} [built]
   [55] ./~/react/lib/ReactUpdates.js 8.54 kB {0} [built]
   [56] ./~/react/lib/CallbackQueue.js 2.44 kB {0} [built]
   [57] ./~/react/lib/PooledClass.js 3.55 kB {0} [built]
   [58] ./~/react/lib/Transaction.js 9.55 kB {0} [built]
   [59] ./~/react/~/fbjs/lib/emptyObject.js 482 bytes {0} [built]
   [60] ./~/react/~/fbjs/lib/containsNode.js 1.43 kB {0} [built]
   [61] ./~/react/~/fbjs/lib/isTextNode.js 628 bytes {0} [built]
   [62] ./~/react/~/fbjs/lib/isNode.js 712 bytes {0} [built]
   [63] ./~/react/lib/instantiateReactComponent.js 4.52 kB {0} [built]
   [64] ./~/react/lib/ReactCompositeComponent.js 27.5 kB {0} [built]
   [65] ./~/react/lib/ReactComponentEnvironment.js 1.67 kB {0} [built]
   [66] ./~/react/lib/ReactPropTypeLocations.js 549 bytes {0} [built]
   [67] ./~/react/lib/ReactPropTypeLocationNames.js 611 bytes {0} [built]
   [68] ./~/react/lib/shouldUpdateReactComponent.js 1.49 kB {0} [built]
   [69] ./~/react/lib/ReactEmptyComponent.js 1.8 kB {0} [built]
   [70] ./~/react/lib/ReactNativeComponent.js 3.02 kB {0} [built]
   [71] ./~/react/lib/validateDOMNesting.js 13.1 kB {0} [built]
   [72] ./~/react/lib/ReactDefaultInjection.js 3.99 kB {0} [built]
   [73] ./~/react/lib/BeforeInputEventPlugin.js 14.9 kB {0} [built]
   [74] ./~/react/lib/EventPropagators.js 5.22 kB {0} [built]
   [75] ./~/react/lib/FallbackCompositionState.js 2.49 kB {0} [built]
   [76] ./~/react/lib/getTextContentAccessor.js 994 bytes {0} [built]
   [77] ./~/react/lib/SyntheticCompositionEvent.js 1.16 kB {0} [built]
   [78] ./~/react/lib/SyntheticEvent.js 5.79 kB {0} [built]
   [79] ./~/react/lib/SyntheticInputEvent.js 1.15 kB {0} [built]
   [80] ./~/react/~/fbjs/lib/keyOf.js 1.11 kB {0} [built]
   [81] ./~/react/lib/ChangeEventPlugin.js 11.5 kB {0} [built]
   [82] ./~/react/lib/getEventTarget.js 930 bytes {0} [built]
   [83] ./~/react/lib/isTextInputElement.js 1.03 kB {0} [built]
   [84] ./~/react/lib/ClientReactRootIndex.js 551 bytes {0} [built]
   [85] ./~/react/lib/DefaultEventPluginOrder.js 1.26 kB {0} [built]
   [86] ./~/react/lib/EnterLeaveEventPlugin.js 3.9 kB {0} [built]
   [87] ./~/react/lib/SyntheticMouseEvent.js 2.2 kB {0} [built]
   [88] ./~/react/lib/SyntheticUIEvent.js 1.64 kB {0} [built]
   [89] ./~/react/lib/getEventModifierState.js 1.3 kB {0} [built]
   [90] ./~/react/lib/HTMLDOMPropertyConfig.js 7.63 kB {0} [built]
   [91] ./~/react/lib/ReactBrowserComponentMixin.js 1.15 kB {0} [built]
   [92] ./~/react/lib/findDOMNode.js 2.17 kB {0} [built]
   [93] ./~/react/lib/ReactDefaultBatchingStrategy.js 1.92 kB {0} [built]
   [94] ./~/react/lib/ReactDOMComponent.js 36.9 kB {0} [built]
   [95] ./~/react/lib/AutoFocusUtils.js 816 bytes {0} [built]
   [96] ./~/react/~/fbjs/lib/focusNode.js 725 bytes {0} [built]
   [97] ./~/react/lib/CSSPropertyOperations.js 5.71 kB {0} [built]
   [98] ./~/react/lib/CSSProperty.js 3.5 kB {0} [built]
   [99] ./~/react/~/fbjs/lib/camelizeStyleName.js 1.03 kB {0} [built]
  [100] ./~/react/~/fbjs/lib/camelize.js 729 bytes {0} [built]
  [101] ./~/react/lib/dangerousStyleValue.js 1.93 kB {0} [built]
  [102] ./~/react/~/fbjs/lib/hyphenateStyleName.js 1 kB {0} [built]
  [103] ./~/react/~/fbjs/lib/hyphenate.js 822 bytes {0} [built]
  [104] ./~/react/~/fbjs/lib/memoizeStringOnly.js 778 bytes {0} [built]
  [105] ./~/react/lib/ReactDOMButton.js 1.15 kB {0} [built]
  [106] ./~/react/lib/ReactDOMInput.js 5.74 kB {0} [built]
  [107] ./~/react/lib/LinkedValueUtils.js 5.18 kB {0} [built]
  [108] ./~/react/lib/ReactPropTypes.js 12.3 kB {0} [built]
  [109] ./~/react/lib/getIteratorFn.js 1.17 kB {0} [built]
  [110] ./~/react/lib/ReactDOMOption.js 2.82 kB {0} [built]
  [111] ./~/react/lib/ReactChildren.js 5.83 kB {0} [built]
  [112] ./~/react/lib/traverseAllChildren.js 6.9 kB {0} [built]
  [113] ./~/react/lib/ReactDOMSelect.js 6.11 kB {0} [built]
  [114] ./~/react/lib/ReactDOMTextarea.js 4.35 kB {0} [built]
  [115] ./~/react/lib/ReactMultiChild.js 14.7 kB {0} [built]
  [116] ./~/react/lib/ReactChildReconciler.js 4.52 kB {0} [built]
  [117] ./~/react/lib/flattenChildren.js 1.65 kB {0} [built]
  [118] ./~/react/~/fbjs/lib/shallowEqual.js 1.28 kB {0} [built]
  [119] ./~/react/lib/ReactEventListener.js 7.51 kB {0} [built]
  [120] ./~/react/~/fbjs/lib/EventListener.js 2.65 kB {0} [built]
  [121] ./~/react/~/fbjs/lib/getUnboundedScrollPosition.js 1.09 kB {0} [built]
  [122] ./~/react/lib/ReactInjection.js 1.37 kB {0} [built]
  [123] ./~/react/lib/ReactClass.js 27.8 kB {0} [built]
  [124] ./~/react/lib/ReactComponent.js 5.04 kB {0} [built]
  [125] ./~/react/lib/ReactNoopUpdateQueue.js 3.94 kB {0} [built]
  [126] ./~/react/lib/ReactReconcileTransaction.js 4.58 kB {0} [built]
  [127] ./~/react/lib/ReactInputSelection.js 4.32 kB {0} [built]
  [128] ./~/react/lib/ReactDOMSelection.js 6.83 kB {0} [built]
  [129] ./~/react/lib/getNodeForCharacterOffset.js 1.66 kB {0} [built]
  [130] ./~/react/~/fbjs/lib/getActiveElement.js 924 bytes {0} [built]
  [131] ./~/react/lib/SelectEventPlugin.js 6.71 kB {0} [built]
  [132] ./~/react/lib/ServerReactRootIndex.js 868 bytes {0} [built]
  [133] ./~/react/lib/SimpleEventPlugin.js 17.4 kB {0} [built]
  [134] ./~/react/lib/SyntheticClipboardEvent.js 1.23 kB {0} [built]
  [135] ./~/react/lib/SyntheticFocusEvent.js 1.12 kB {0} [built]
  [136] ./~/react/lib/SyntheticKeyboardEvent.js 2.76 kB {0} [built]
  [137] ./~/react/lib/getEventCharCode.js 1.56 kB {0} [built]
  [138] ./~/react/lib/getEventKey.js 2.93 kB {0} [built]
  [139] ./~/react/lib/SyntheticDragEvent.js 1.13 kB {0} [built]
  [140] ./~/react/lib/SyntheticTouchEvent.js 1.33 kB {0} [built]
  [141] ./~/react/lib/SyntheticWheelEvent.js 1.99 kB {0} [built]
  [142] ./~/react/lib/SVGDOMPropertyConfig.js 3.8 kB {0} [built]
  [143] ./~/react/lib/ReactDefaultPerf.js 8.63 kB {0} [built]
  [144] ./~/react/lib/ReactDefaultPerfAnalysis.js 5.79 kB {0} [built]
  [145] ./~/react/~/fbjs/lib/performanceNow.js 844 bytes {0} [built]
  [146] ./~/react/~/fbjs/lib/performance.js 612 bytes {0} [built]
  [147] ./~/react/lib/ReactVersion.js 379 bytes {0} [built]
  [148] ./~/react/lib/renderSubtreeIntoContainer.js 463 bytes {0} [built]
  [149] ./~/react/lib/ReactDOMServer.js 766 bytes {0} [built]
  [150] ./~/react/lib/ReactServerRendering.js 3.3 kB {0} [built]
  [151] ./~/react/lib/ReactServerBatchingStrategy.js 673 bytes {0} [built]
  [152] ./~/react/lib/ReactServerRenderingTransaction.js 2.3 kB {0} [built]
  [153] ./~/react/lib/ReactIsomorphic.js 2.05 kB {0} [built]
  [154] ./~/react/lib/ReactDOMFactories.js 3.36 kB {0} [built]
  [155] ./~/react/lib/ReactElementValidator.js 10.8 kB {0} [built]
  [156] ./~/react/~/fbjs/lib/mapObject.js 1.47 kB {0} [built]
  [157] ./~/react/lib/onlyChild.js 1.21 kB {0} [built]
  [158] ./~/react/lib/deprecated.js 1.77 kB {0} [built]
  [159] ./~/react-dom/index.js 63 bytes {0} [built]

ERROR in ./app/config/routes.js
Module parse failed: C:\React-Fundamentals-video12\app\config\routes.js Unexpected token (14:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (14:2)
    at Parser.pp$4.raise (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$1.parseVar (C:\React-Fundamentals-video12\node_modules\webpack\node_modules\acorn\dist\acorn.js:1034:28)
 @ ./app/index.js 3:13-39
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 534 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 653 bytes {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 533 kB {0} [built]
        [2](webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.
Terminate batch job (Y/N)?

**Comment by ykmargate** [comment]
I will be very appreciate if somebody can give me an idea what is wrong with compiling code under windows.
I was able to run all applications from Video 8 - Video 11 and got a problem with video 12 only,
I just tested video 12 on my Linux box (VM) and it works.

**Comment by matsieftw** [comment]
The error info you provided says there is an unexpected token in line 14 of the routes file. Go look there and try to find out what is going on.

**Comment by ykmargate** [comment]
You didn't read my last message. Video 12 works on Linux box and doesn't work on any windows computer.

**Comment by matsieftw** [comment]
I read your message and I'm saying the issue appears to be on line 14 of your routes file according to the error and you should look there. It could be a line ending issue or something like that.

**Comment by rohitpujar** [comment]
I'm using PyCharm IDE on Windows. When I run your code, I get the following error:

> github-battle@1.0.0 production C:\Workspace\PyCharmProjects\github-battle
> webpack -p

Hash: 21e367e251c35209471c
Version: webpack 1.13.2
Time: 1949ms
          Asset       Size  Chunks             Chunk Names
index_bundle.js  289 bytes       0  [emitted]  main
     index.html  321 bytes          [emitted]
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./app/index.js
Module build failed: ReferenceError: [BABEL] C:\Workspace\PyCharmProjects\github-battle\app\index.js: Unknown option: C:\Workspace\PyCharmProjects\github-battle\node_modules\react\react.js.Children. Check out http://babeljs.io/docs/usage/options/ for more info
(While processing preset: "C:\Workspace\PyCharmProjects\github-battle\node_modules\react\react.js")
    at Logger.error (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\options\option-manager.js:220:20)
    at C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\options\option-manager.js:259:14
    at C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328:22
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\options\option-manager.js:269:20)
    at OptionManager.mergePresets (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\options\option-manager.js:258:10)
    at OptionManager.mergeOptions (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\options\option-manager.js:243:14)
    at OptionManager.init (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\options\option-manager.js:373:12)
    at File.initOptions (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\index.js:221:65)
    at new File (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\file\index.js:141:24)
    at Pipeline.transform (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (C:\Workspace\PyCharmProjects\github-battle\node_modules\babel-loader\index.js:131:12)
 @ multi main
Child html-webpack-plugin for "index.html":
        + 3 hidden modules

Is there a problem with modules?

--- Fix -- 
Installed this module:

npm install --save-dev babel-preset-react

**Comment by rmbrntt** [comment]
I've unfortunately hit the same issue. 

Seems to be a common issue on windows:
https://github.com/babel/babel-loader/issues/198
https://github.com/webpack/webpack/issues/2462

I first got the error in video12 when setting up react-addons-css-transition-group, style-loader, and css-loader.

**Comment by adriennemcd** [comment]
I ran into the same error while working through video 12 - on windows 10.  @rohitpujar's solution solved the issue for me:  
npm install --save-dev babel-preset-react

**Comment by ykmargate** [comment]
Thanks. It solved issue.

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!
