### ISSUE TITLE
webpack-dev-server not working

### ISSUE THREAD

**Issue by markandersonus** [ReactjsProgram/React-Fundamentals#76]
I get this when i run npm run start

> github-battle@1.0.0 start C:\reactJS\github-battle
> webpack-dev-server --open

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: addMembership EHOSTUNREACH
    at exports._errnoException (util.js:1014:11)
    at Socket.addMembership (dgram.js:579:11)
    at Socket.<anonymous> (C:\reactJS\github-battle\node_modules\multicast-dns\index.js:53:16)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at startListening (dgram.js:144:10)
    at _handle.lookup (dgram.js:249:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github-battle@1.0.0 start: `webpack-dev-server --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github-battle@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by markandersonus** [comment]
had to use another port --port 3000 --open
